language: go

go:
    - 1.13.x
    - tip

script:
    - go test -tags=integration -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
    - bash <(curl -s https://codecov.io/bash)
