{
 "title": "SpeakerDeck",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "speakerdeck_scrape_collector_state"
    }
   ]
  },
  {
   "title": "Views per deck",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "speakerdeck_views", "legendFormat": "{{ deck }}" }
   ]
  },
  {
   "title": "Scrape duration per sec",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(speakerdeck_scrape_collector_duration_seconds{} [5m])"
    }
   ]
  },
  {
   "title": "Stars by author",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(speakerdeck_stars) by (author)",
     "legendFormat": "{{ author }}"
    }
   ]
  }
 ]
}